version: "3.2"

services:
    cr-producer:
        image: cormorack/cr-producer:0.1.1
        environment:
            - CR_PRODUCER_OOI_USERNAME=${OOI_USERNAME}
            - CR_PRODUCER_OOI_TOKEN=${OOI_TOKEN}
            - CR_PRODUCER_KAFKA_HOST=kafka
            - CR_PRODUCER_KAFKA_PORT=29092
        depends_on:
            - kafka
        networks:
            - io2network
    kafka-kv:
        build:
            context: ../..
            dockerfile: ../../resources/docker/Dockerfile
        image: cormorack/cava-realtime-client:latest
        ports:
          - 8081:8081
        links:
          - kafka
        depends_on:
          - cr-producer
        command:
          - --streams-props
          - bootstrap.servers=kafka:29092
          - num.standby.replicas=1
          - --application-id
          - my-streams-processor
          - --hostname
          - localhost
        networks:
            - io2network
    redis-service:
        image: redis:alpine3.13
        ports:
          - 6379:6379
        expose:
          - 6379
        networks:
          - io2network
    zookeeper:
        image: bitnami/zookeeper:3.6.3
        environment:
          ALLOW_ANONYMOUS_LOGIN: "yes"
        ports:
          - 2181:2181
        networks:
          - io2network
    kafka:
        image: bitnami/kafka:2.8.0
        environment:
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:29092
            - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_CFG_MESSAGE_MAX_BYTES=2000000
            - KAFKA_CFG_OFFSETS_RETENTION_MINUTES=2
            # Clean up settings below
            - KAFKA_CFG_LOG_CLEANUP_POLICY=delete
            - KAFKA_CFG_LOG_RETENTION_MS=900000 # 15 minutes
            - KAFKA_CFG_LOG_ROLL_MS=900000 # 15 minutes
            - KAFKA_CFG_LOG_SEGMENT_DELETE_DELAY_MS=1
            - KAFKA_CFG_LOG_RETENTION_CHECK_INTERVALS_MS=5000 # 5 Seconds
        ports:
            - 9092:9092
            - 29092:29092
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - zookeeper
        depends_on:
            - zookeeper
        networks:
            - io2network

networks:
    io2network:
