{{- $serviceName := default (include "cava-realtime-client.name" .) -}}
  {{- $servicePortName := .Values.service.portName -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "cava-realtime-client.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
  name: {{ $serviceName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ $servicePortName }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "cava-realtime-client.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
status:
  loadBalancer: {}